{% set name = "trends_earth_schemas" %}
{% set version = "2.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ConservationInternational/trends.earth-schemas/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 85ca5a800e5eea973f21582780d365cfd1537790578a98a91e5998ee1af03872

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - marshmallow >=3.18.0
    - marshmallow-dataclass ==8.5.10

test:
  imports:
    - te_schemas


about:
  home: https://github.com/ConservationInternational/trends.earth-schemas
  license: MIT
  license_file: LICENSE
  summary: trends.earth-schemas is a python package that stores the schemas used for internal handling of the results of trends.earth analyses.

extra:
  recipe-maintainers:
    - marie59
